name: build-godot-stuff
on: 
  push:
    branches:
      - master

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: tankgrid
  PROJECT_PATH: .

jobs:
  export-web:
    name: Create GHPages
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Patch src
        env:
          BACKURL: ${{ vars.BACKEND_URL }}
        run: |
          sed -i 's@"http://127.0.0.1:8001"@"'"${BACKURL}"'"@g' assets/web/dataaccess.gd
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
          cp "$EXPORT_DIR/web/index.html" "$EXPORT_DIR/web/battle_loader.html"
          cp "$EXPORT_DIR/web/index.html" "$EXPORT_DIR/web/manual.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.

